package com.project.FSGapi.ENUM;

public enum AccountName {
    CASH,
    TRADE_PAYABLE,
    TRADE_RECEIVABLE,
    INVENTORY,
    BANK_ACCOUNT,
    VAT_DEPOSIT,
    SHAREHOLDER_INVESTMENT,
    PREPAYMENT,
    TAX_LIABILITY,
    INCOME,
    SALES,
    COS,
    DEPRECIATION_EXP,
    SALARIES_EXP,
    BANK_COMMISSION_EXP,
    RENT_EXP,
    UTILITIES_EXP,
    INTEREST_EXP,
    OTHER_EXP,
    SOCIAL_PMT_EXP
}
