package com.project.FSGapi.ENUM;

public enum AccountType {
    INCOME,
    COGS,
    TOTAL_INCOME,
    EXPENSES,
    TOTAL_EXPENSES,
    GROSS_PROFIT,
    PBT,
    INCOME_TAX,
    NET_PROFIT,
    ASSET,
    CURRENT_ASSET,
    NON_CURRENT_ASSET,
    TOTAL_ASSET,
    LIABILITY,
    CURRENT_LIABILITY,
    NON_CURRENT_LIABILITY,
    TOTAL_LIABILITY,
    EQUITY,
    SHAREHOLDER_INVESTMENT,
    RETAINED_EARNINGS,
    TOTAL_EQUITY,
    TOTAL_LIABILITY_AND_EQUITY
}
