package com.project.FSGapi.ENUM;

public enum AccountType {
    REVENUE,
    COGS,
    TOTAL_INCOME,
    EXPENSES,
    TOTAL_EXPENSES,
    GROSS_PROFIT,
    PBIT,
    INCOME_TAX,
    INTEREST_EXPENSE,
    NET_PROFIT,
//    ASSET,
//    CURRENT_ASSET,
//    NON_CURRENT_ASSET,
//    TOTAL_ASSET,
//    LIABILITY,
//    CURRENT_LIABILITY,
//    NON_CURRENT_LIABILITY,
//    TOTAL_LIABILITY,
//    EQUITY,
//    SHAREHOLDER_INVESTMENT,
//    RETAINED_EARNINGS,
//    TOTAL_EQUITY,
//    TOTAL_LIABILITY_AND_EQUITY
}
